version: '2'
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  www:
    image: nickbreen/wp-setup
    command: /sbin/my_init -- setuser wp wp server --host=0.0.0.0 --docroot=/var/www
    volumes_from:
      - wp
    links:
      - db:mysql
    ports:
      - 80:8080

  wp:
    build: .
    image: nickbreen/wp-setup
    links:
      - db
    environment:
      CRON_D_WP: |
        PATH=/usr/local/bin:$$PATH
        * * * * * wp sh /etc/container_environment/WP_CRON 2>&1 | logger --tag wp-cron
        @reboot root setuser wp wp-setup 2>&1 | logger --tag wp-reboot
      WP_CRON: |
        wp cron event list --format=csv --fields=hook,next_run_relative | awk -F ',' '$$2 == "now" {print $$1}' | xargs -r -l1 wp cron event run
      WP_DB_HOST: db
      WP_DB_NAME: wordpress
      WP_DB_USER: wordpress
      WP_DB_PASSWORD: wordpress
      WP_DB_ROOT_PASSWORD: example
      WP_LOCALE: en_NZ
      WP_VERSION: 4.5.3
      WP_TITLE: Main
      WP_SUBDOMAINS: "yes"
      WP_URL: http://main.dev
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: admin
      WP_ADMIN_EMAIL: admin@main.dev
      WP_EXTRA_PHP: |
        define('DISABLE_WP_CRON', TRUE);
      WP_COMMANDS_0: |
        export TERM=dumb
        wp plugin install jetpack --activate-network
        wp site list
        wp theme list
        wp plugin list
        wp --version

        wp-safecss https://api.github.com/gists/f006de1d42490a90a0ebaf4596d09102 file0.css $GH_AUTH

      WP_SITES_0: |
        SLUG=site14
        DOMAIN=dev
        HOST=$$SLUG.$$DOMAIN
        wp-site-create $$SLUG $$HOST http://$$HOST "Site 14"
        wp --url=$$HOST theme activate twentyfourteen

        SLUG=site15
        DOMAIN=dev
        HOST=$$SLUG.$$DOMAIN
        wp-site-create $$SLUG $$HOST http://$$HOST "Site 15"
        wp --url=$$HOST theme activate twentyfifteen
