db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress

wp:
  build: .
  command: [ "/sbin/my_init", "--", "setuser", "wp", "bash", "-l", "-c", "while ! wp server --host=0.0.0.0 --docroot=/var/www; do sleep 5; done" ]
  links:
    - db:mysql
  ports:
    - 80:8080
  environment:
    CRON_D_WP: |
      PATH=/usr/local/bin:$$PATH
      * * * * * wp wp cron event list --format=csv --fields=hook,next_run_relative | awk -F ',' '$$2 == "now" {print $$1}' | xargs -r -l1 wp cron event run

setup:
  build: .
  links:
    - db:mysql
  volumes_from:
    - wp
  environment:
    WP_TITLE: Main
    WP_SUBDOMAINS: "yes"
    WP_URL: http://main.dev
    WP_ADMIN_USER: admin
    WP_ADMIN_PASSWORD: admin
    WP_ADMIN_EMAIL: webmaster+admin@foobar.net.nz
    WP_EXTRA_PHP: |
      define('DISABLE_WP_CRON', TRUE);
      @define('COOKIE_DOMAIN', $$_SERVER[ 'HTTP_HOST' ]);
    WP_COMMANDS_1: |
      set -x
      ID=$$(wp site list --fields=blog_id --domain=site1.dev | sed 1d)
      if [ ! $$ID ]
      then
        ID=$$(wp site create --slug=site1 --title="Site 1" --porcelain)
        wp db query "UPDATE wp_blogs SET domain = 'site1.dev' WHERE blog_id = $$ID"
      fi
      wp --url=http://site1.dev option update siteurl http://site1.dev
      wp --url=http://site1.dev option update home http://site1.dev
      wp site list
    WP_COMMANDS_2: |
      set -x
      ID=$$(wp site list --fields=blog_id --domain=site2.dev | sed 1d)
      if [ ! $$ID ]
      then
        ID=$$(wp site create --slug=site2 --title="Site 2" --porcelain)
        wp db query "UPDATE wp_blogs SET domain = 'site2.dev' WHERE blog_id = $$ID"
      fi
      wp --url=http://site2.dev option update siteurl http://site2.dev
      wp --url=http://site2.dev option update home http://site2.dev
      wp site list
