version: '3.5'

volumes:
  www:

networks:
  wp: {}

services:
  db:
    image: mysql:5.6
    networks:
    - wp
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  memcache:
    image: memcached
    command: memcached -m 256 -vv
    networks:
    - wp

  www:
    image: nickbreen/wp-www:v3.0.0
    depends_on:
    - memcache
    - php
    volumes:
    - www:/var/www:rw
    - ./phpinfo.php:/var/www/phpinfo.php:ro
    - ./default.conf:/etc/apache2/sites-available/000-default.conf:ro
    networks:
      wp:

  php:
    image: nickbreen/wp-php:v3.0.0
    depends_on:
    - memcache
    - db
    volumes:
    - www:/var/www:rw
    - ./phpinfo.php:/var/www/phpinfo.php:ro
    - ./www.conf:/etc/php/7.0/fpm/pool.d/www.conf:ro
    networks:
      wp:
        aliases:
        - fastcgi

  wp:
    depends_on:
    - www
    image: nickbreen/wp-cli:v3.0.0
    command: /sbin/my_init -- /usr/local/bin/wp.sh
    tmpfs:
    - /tmp
    volumes:
    - www:/var/www:rw
    - ./wp-cli.yml:/wp-cli.yml:ro
    - ./wp.sh:/usr/local/bin/wp.sh:ro
    networks:
      wp:
    

