db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress

wp-setup:
  build: .
  links:
    - db:mysql
  volumes_from:
    - wp
  environment:
    WP_EXTRA_PHP: |-
      define('DISABLE_WP_CRON', true);
    CRON_D_WP: |-
      PATH=/usr/local/bin:$$PATH
      * * * * * wp wp cron event list --format=csv --fields=hook,next_run_relative --path=/var/www | awk -F ',' '$$2 == "now" {print $$1}' | xargs -r -l1 wp cron event run --path=/var/www
    WP_URL: http://wp.dev
    WP_ADMIN_USER: admin
    WP_ADMIN_PASSWORD: admin
    WP_ADMIN_EMAIL: admin@wp.dev
    WP_PLUGINS: |-
      rest-api
    GH_PLUGINS: |-
      WP-API/OAuth1
      WP-API/Basic-Auth
    GH_THEMES: |-
      CherryFramework/CherryFramework

wp:
  build: .
  command: [ "/sbin/my_init", "--", "setuser", "wp", "bash", "-l", "-c", "while ! wp server --host=0.0.0.0 --docroot=/var/www; do sleep 5; done" ]
  links:
    - db:mysql
  ports:
    - 81:8080
