version: '2'
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  www:
    image: nickbreen/wp-cli
    command: [ "/sbin/my_init", "--", "setuser", "wp", "bash", "-l", "-c", "while ! wp server --host=0.0.0.0 --docroot=/var/www; do sleep 5; done" ]
    volumes_from:
      - wp
    links:
      - db:mysql
    ports:
      - 8080:8080
    environment:
      CRON_D_WP: |
        PATH=/usr/local/bin:$$PATH
        * * * * * wp wp cron event list --format=csv --fields=hook,next_run_relative | awk -F ',' '$$2 == "now" {print $$1}' | xargs -r -l1 wp cron event run

  wp:
    build: .
    image: nickbreen/wp-setup
    links:
      - db:mysql
    environment:
      WP_LOCALE: en_NZ
      WP_VERSION: 4.4.2
      WP_TITLE: Main
      WP_SUBDOMAINS: "yes"
      WP_URL: http://main.dev:8080
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: admin
      WP_ADMIN_EMAIL: admin@main.dev
      WP_EXTRA_PHP: |
        define('DISABLE_WP_CRON', TRUE);
      WP_COMMANDS_0: |
        set -e

        wp bitbucket theme install mwins/wordpress-theme-basic
        wp github theme install wpbrasil/odin
        wp github plugin install ericrallen/wp-base-plugin

        wp plugin install jetpack --activate-network

      WP_COMMANDS_END: |
        export TERM=dumb
        wp site list
        wp theme list
        wp plugin list
        wp --version
      WP_SITES_1: |
        SLUG=site14
        DOMAIN=dev
        HOST=$$SLUG.$$DOMAIN:8080
        wp-site-create $$SLUG $$HOST https://$$HOST "Site 14"
        wp --url=$$HOST theme activate twentyfourteen
      WP_SITES_2: |
        SLUG=site15
        DOMAIN=dev
        HOST=$$SLUG.$$DOMAIN:8080
        wp-site-create $$SLUG $$HOST https://$$HOST "Site 15"
        wp --url=$$HOST theme activate twentyfifteen
