db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress

wp:
  build: .
  command: [ "/sbin/my_init", "--", "setuser", "wp", "bash", "-l", "-c", "while ! wp server --host=0.0.0.0 --docroot=/var/www; do sleep 5; done" ]
  links:
    - db:mysql
  ports:
    - 80:8080
  environment:
    CRON_D_WP: |
      PATH=/usr/local/bin:$$PATH
      * * * * * wp wp cron event list --format=csv --fields=hook,next_run_relative | awk -F ',' '$$2 == "now" {print $$1}' | xargs -r -l1 wp cron event run

setup:
  build: .
  links:
    - db:mysql
  volumes_from:
    - wp
  environment:
    WP_LOCALE: en_NZ
    WP_VERSION: 4.4.2
    WP_TITLE: Main
    WP_SUBDOMAINS: "yes"
    WP_URL: http://main.dev
    WP_ADMIN_USER: admin
    WP_ADMIN_PASSWORD: admin
    WP_ADMIN_EMAIL: admin@main.dev
    WP_EXTRA_PHP: |
      define('DISABLE_WP_CRON', TRUE);
    WP_COMMANDS_0: |
      wp --url=http://main.dev theme activate twentyfifteen
    WP_COMMANDS_1: |
      new_site sitea sitea.dev http://sitea.dev "Site A"
      wp --url=http://sitea.dev theme activate twentyfourteen
    WP_COMMANDS_2: |
      new_site siteb siteb.dev http://siteb.dev "Site B"
      wp --url=http://sitea.dev theme activate twentythirteen
    WP_COMMANDS_END: |
      wp site list
